apiVersion: apps/v1
kind: Deployment
metadata:
  name: genparker-philanthropy
  labels:
    app: backend-philanthropy
spec:
  serviceName: genparker-philanthropy
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: backend-philanthropy
  template:
    metadata:
      labels:
        app: backend-philanthropy
    spec:
      containers:
        - name: backend-philanthropy
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockersecret
---
apiVersion: v1
kind: Service
metadata:
  name: genparker-philanthropy-svc
  labels:
    app: backend-philanthropy
spec:
  clusterIP: None
  ports:
    - name: http
      port: 59595
  selector:
    app: backend-philanthropy
