# https://github.com/nginx-proxy/nginx-proxy
version: '3.7'
services:
  # nginx-docker-gen:
  #   image: nginxproxy/docker-gen
  #   restart: always
  #   container_name: nginx-proxy-gen
  #   networks:
  #     - nginx
  #     - nginx-canopeum
  #     - nginx-genparker
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:rw
  #     - nginx-template:/etc/docker-gen/templates

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: nginx-proxy
    networks:
      - nginx
      - nginx-canopeum
      - nginx-genparker
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/live/releaftrees.life:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    container_name: nginx-proxy-acme
    networks:
      - nginx
      - nginx-canopeum
      - nginx-genparker
    depends_on:
      - nginx-proxy
      - nginx-proxy-gen
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      # - NGINX_DOCKER_GEN_CONTAINER=nginx-proxy-gen
      - DEFAULT_EMAIL=andrew.parker@beslogic.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/letsencrypt/live/releaftrees.life:/etc/nginx/certs
      - nginx-acme:/etc/acme.sh
      - nginx-html:/usr/share/nginx/html

volumes:
  nginx-acme:
    external: true
  nginx-html:
    external: true
  nginx-template:
    external: true

networks:
  nginx:
    external: true
  nginx-canopeum:
    external: true
  nginx-genparker:
    external: true