# https://github.com/nginx-proxy/nginx-proxy
version: '3.7'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6
    restart: always
    networks:
      - nginx
      - nginx-canopeum
      - nginx-genparker
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/live/releaftrees.life:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"

networks:
  nginx:
    external: true
  nginx-canopeum:
    external: true
  nginx-genparker:
    external: true