# https://github.com/nginx-proxy/nginx-proxy
version: '3.7'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    networks:
      - nginx
      - nginx-canopeum
      - nginx-genparker
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    networks:
      - nginx
      - nginx-canopeum
      - nginx-genparker
    environment:
      - DEFAULT_EMAIL=andrew.parker@beslogic.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx:/etc/acme.sh
volumes:
  nginx:

networks:
  nginx:
    external: true
  nginx-canopeum:
    external: true
  nginx-genparker:
    external: true