# https://github.com/nginx-proxy/nginx-proxy
version: '3.7'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: nginx-proxy
    labels:
      - 'com.github.nginx-proxy.nginx'
    networks:
      - nginx
      - nginx-canopeum
      - nginx-genparker
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/live/releaftrees.life:/etc/nginx/certs
      - nginx-html:/usr/share/nginx/html
      - nginx-config:/etc/nginx/conf.d
    ports:
      - '80:80'
      - '443:443'

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    container_name: nginx-proxy-acme
    networks:
      - nginx
      - nginx-canopeum
      - nginx-genparker
    depends_on:
      - nginx-proxy
      - nginx-proxy-gen
    environment:
      - DEFAULT_EMAIL=andrew.parker@beslogic.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/letsencrypt/live/releaftrees.life:/etc/nginx/certs
      - nginx-acme:/etc/acme.sh
      - nginx-html:/usr/share/nginx/html

  Watchtower:
    container_name: Watchtower
    image: containrrr/watchtower
    command: --debug true --interval 60 --include-restarting true --include-stopped true --cleanup true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_INCLUDE_RESTARTING=true

volumes:
  nginx-acme:
    external: true
  nginx-html:
    external: true
  nginx-template:
    external: true
  nginx-config:
    external: true

networks:
  nginx:
    external: true
  nginx-canopeum:
    external: true
  nginx-genparker:
    external: true
