apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 'base/network'
  - 'base/platform'
patches:
  - path: ./configs/platform/platform.yml
  - path: ./configs/network/network.yml
