version: '3.7'
services:
  backend:
    image: ghcr.io/beslogic/releaf_backend_philantropy:latest
    restart: always
    entrypoint: [ '/bin/sh', '-c', '\
      export GenParker__KafkaMongoDbSettings__ConnectionString=$$(cat /run/secrets/releaf-genparker-mongodb) ;\
      export GenParker__GenParkerMongoDbSettings__ConnectionString=$$(cat /run/secrets/releaf-genparker-mongodb) ;\
      export Releaf__MongoDbSettings__ConnectionString=$$(cat /run/secrets/releaf-genparker-mongodb) ;\
      source /entrypoint.sh' ]
    secrets:
      - releaf-genparker-mongodb

secrets:
    releaf-genparker-mongodb:
      external: true